import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { logout } from "@/lib/action";

export const metadata: Metadata = {
  title: "Next auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div>
          <ul>
            <li>
              <Link href="/">home</Link>
            </li>
            <li>
              <Link href="/login">login</Link>
            </li>
            <li>
              <Link href="/register">register</Link>
            </li>
            <li>
              <Link href="/dashboard">dashboard</Link>
            </li>
            <li>
              <form action={logout}>
                <button>로그아웃</button>
              </form>
            </li>
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
